### ISSUE TITLE
Access to IconData obj

### ISSUE THREAD

**Issue by AndreLuizNogueira** [galonsos/la_icons#1]
Hi. I just tried to move from the LineIcons package, but with the actual usage, I don't think anyone would be able to move.

I have 2 apps that use Linecons, and because it was returning an IconData obj, just like the official flutter icons, I created my own functions and enums around it using both libraries. Doing a refactoring like this wouldn't work for both.

Can you add some way for us to access the IconData obj again? Even though this is a rewrite, it's not a refactoring.

**Comment by galonsos** [comment]
Hi, André. 

Thanks for the insights. However, this is precisely the reason this package was created from scratch, instead of continuing the LineIcons library. If you're using `LineIcons`, I suggest you stick to it; `LaIcons` is only recommended for new projects from now on.

Anyhow, what's exactly what you need? `LaIcons` class holds the `IconData` objects as consts, through the `getByName` method and via the `iconMap` map. Can you provide an example of what are you expecting?

Regards

**Comment by AndreLuizNogueira** [comment]
> Hi, André.
> 
> Thanks for the insights. However, this is precisely the reason this package was created from scratch, instead of continuing the LineIcons library. If you're using `LineIcons`, I suggest you stick to it; `LaIcons` is only recommended for new projects from now on.
> 
> Anyhow, what's exactly what you need? `LaIcons` class holds the `IconData` objects as consts, through the `getByName` method and via the `iconMap` map. Can you provide an example of what are you expecting?
> 
> Regards

I just understood the problem, it's something with the autocomplete (ctrl + space)... it's not showing the LaIcons, with the s... and when I looked at the sample code you used icon instead of icons. I was trying LaIcons.lasShippingFast().

![image](https://github.com/user-attachments/assets/ae12fe27-d2cb-4fb7-8426-426d98c90a2b)

Now I managed to make it work, just one thing: some have "las" at the beginning and some have "lab", was it on purpose or was it a typo?

**Comment by galonsos** [comment]
From the `read.me` file:

_Styling: there're three different styles: brands, regular and solid. Icons are prefixed `lab`, `lar` and `las` respectively. It also helps avoiding name conflicts, such as alternate-comment, which exists for regular and solid styles, turning into `lar-alternate-comment` and `las-alternate-comment`._

It has to do with the way Icons8 arranged the icons, in three different TTF fonts. Merging all three in just one catalog was not an option, since some icons from different fonts share the same name. They're probably the same glyphs, but I wanted to be loyal to the creator's intention and, secondly, be ready for changes in the fonts in the future.
